version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: ORM_mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: FakeFootChampion
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ORM_phpmyadmin_container
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8093:80"

  php:
    build:
      context: ./  
      dockerfile: Dockerfile
    container_name: ORM_php_container
    restart: always
    volumes:
      - .:/var/www/html  
      - ./Public:/var/www/html
    ports:
      - "8080:80"

volumes:
  mysql_data:

